### ISSUE TITLE
[Android] Default fullscreen configuration is annoying to get back home when no physic buttons

### ISSUE THREAD

**Issue by nicosomb** [esviji/esviji#159]
Hello, 

On my Android smartphone (5.0.2), esviji starts with a fullscreen. But I can't get back to home because I don't have physic buttons on my phone. 

I have to type on the top of my screen to display the status and menu bars (at the top and at the bottom). 

Mainly, I think Android applications don't start in fullscreen mode. 

I made a [screenshot](https://cloud.githubusercontent.com/assets/121870/12393206/8d5b3f20-bdf4-11e5-8539-402814c6e84e.png), but it's not very interesting (its only a screenshot with esviji in fact...)

**Comment by nhoizey** [comment]
Thanks for the report, I'll look for a solution ASAP

**Comment by nhoizey** [comment]
@nicosomb can you check if it's fixed with release 2.1.3? Thanks

**Comment by nicosomb** [comment]
:+1:

**Comment by nhoizey** [comment]
\o/
