### ISSUE TITLE
Looking for iOS beta testers

### ISSUE THREAD

**Issue by nhoizey** [esviji/esviji#166]
Please comment with the e-mail address you want me to add to TestFlight

You can also [join the Slack channel](http://esviji.com/2016/01/join-us-on-slack.html) and DM me if you don't want to share your e-mail address here.

**Comment by shinze** [comment]
Hey, I'd love to test : gaetan(dot)ark(at)gmail.com. On an iPhone6.

**Comment by mikaelrandy** [comment]
OK to test
mikael(dot)randy(at)gmail(dot)com
iPhone 6

**Comment by nhoizey** [comment]
@shinze @mikaelrandy done!

**Comment by mikaelrandy** [comment]
I originally downloaded v2.1.3 and by trying, I found some problems.
But yesterday, i updated to v2.1.4, and since there is no visible worries.

I continue to test, but great work, the game is awesome.

**Comment by nhoizey** [comment]
Thanks a lot!

**Comment by nhoizey** [comment]
Beta for v2.1.5 is available

**Comment by sebastienleblanc** [comment]
tu m'ajoutes? 6s ios9.3 beta prenom . nom at gmail . Com

**Comment by nhoizey** [comment]
@sebastienleblanc fait ! Merci !

**Comment by mikaelrandy** [comment]
I continue to play to test.

Some little feedbacks :
* sometime, when i "drop" the ball, there is a small freeze, and when it is released, the ball is where it should have been without the freeze. As is it only the display who freeze, but not the game.
* when someone call me during a game, the game crash when i go back to it.

**Comment by nhoizey** [comment]
Thanks for the feedbacks!

- It is indeed only the display that freezes (I don't know why…), because the animation is using SMIL, which deals alone with the clock
- What type of crash do you have after a call? The game stops, or it is still there but doesn't work?

**Comment by mikaelrandy** [comment]
* okay. If you are aware of this, it's fine
* game stop, applications list screen is displayed and game is no more in background applications

**Comment by nhoizey** [comment]
No more in background applications, that's new… :-/

Can you open a specific issue on this topic?

Thanks.

**Comment by nhoizey** [comment]
Not true anymore: http://esviji.com/2016/02/android-and-ios-apps-development-stopped.html
