### ISSUE TITLE
Looking for Android beta testers

### ISSUE THREAD

**Issue by nhoizey** [esviji/esviji#170]
To join the beta testers of the Android version, you just have to go to this page: https://play.google.com/apps/testing/com.esviji.app

You can also [join the Slack channel](http://esviji.com/2016/01/join-us-on-slack.html) to give your feedback.

**Comment by nhoizey** [comment]
Beta for v2.1.5 is available, with a new WebView that might fix the freeze issue ( #163 )

**Comment by SphinxKnight** [comment]
sphinx _ knight chez hotmail . fr

**Comment by nhoizey** [comment]
@SphinxKnight done!

**Comment by nhoizey** [comment]
Not true anymore: http://esviji.com/2016/02/android-and-ios-apps-development-stopped.html
